/* *****************************************
 * CSCI 205 - Software Engineering and Design
 * Fall 2024
 * Instructor: Prof. Lily
 *
 * Name: Tue Nhi Cao
 * Section: 10am
 * Date: 12/2/2024
 * Time: 10:51 AM
 *
 * Project: csci205_final_project
 * Package: org.ChrisMeiersMollyNhi.ApiCall
 * Class: callAPI
 *
 * Description:
 * A class that provides methods to interact with the QA model for generating
 * hints and checking the validity of English words using the Groq API.
 * ****************************************
 */

package org.ChrisMeiersMollyNhi.ApiCall;

public class CallAPI {
    /**
     * Generates a concise hint for a given word by sending a request to the QA model.
     * The hint will be generated by the model, and only the hint (with no extra text) will be returned.
     *
     * @param word the word for which the hint is to be generated
     * @return a string containing the generated hint for the word
     */
    public static String generateHint(String word){
        QA model = new QA();
        return model.generate("Provide a clear, concise hint for the word" + word + "." +
                "Only the hint should be returned. No extra introductory or explanatory text.");
    }

    /**
     * Checks if the provided word is a valid English word by sending a request to the QA model.
     * The model will return true if the word is valid in standard English and false otherwise.
     *
     * @param word the word to check for validity
     * @return a string containing either "true" or "false", indicating whether the word is valid
     */
    public static String checkValid(String word){
        QA model = new QA();
        return model.generate("Determine if the word " + word + " has meaning in standard English. " +
                "Return true if it is a valid English word and false otherwise. " +
                "Do not provide any explanation or additional text; only return true or false.");
    }
}